### PR TITLE
chore: Setup notion toolchain

### PR DESCRIPTION
**Pull request by mattsjones**

### CODE REVIEW

**Comment by mattsjones** [comment]
Notion doesn't work that way. You specify an exact version and it just ensures you use it. You don't need to run any commands like with `nvm` though so this doesn't add any time to set up or anything. Also, Notion is purely for dev experience, it's not related to the engines field.

**Comment by mattsjones** [comment]
To be clear, I created this PR by running:
```
notion pin node 10
notion pin yarn latest
```

Notion just picked the latest version of 10 as the pinned one.

**Comment by markdalgleish** [comment]
Is this now out of sync with .nvmrc?

**Comment by mattsjones** [comment]
nvm is pointing to `lts/*` so they're actually aligned. At least for now. I really do think notion is the way to go though.

**Pull request merged**
